import { Bot, BriefcaseBusiness, Check, ChevronRight, FileText, Heart, Play, Plus, Search, ShieldCheck, Sparkles, UsersRound, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { NavLink, useLocation, useNavigate } from 'react-router-dom';

type Agent = { name: string; description: string; category: string; owner: string; status: string; icon: typeof Bot; tone: string };

const categories = ['全部', '客服应答', '文案创作', '数据分析', '行政办公', '销售支持', '企业通用'];
const agents: Agent[] = [
  { name: '客户沟通助手', description: '整理客户信息，生成跟进建议和沟通摘要。', category: '销售支持', owner: '团队共享', status: '已发布', icon: UsersRound, tone: 'indigo' },
  { name: '企业制度问答', description: '基于企业制度和流程资料，快速回答常见问题。', category: '企业通用', owner: '人事团队', status: '已发布', icon: FileText, tone: 'emerald' },
  { name: '周报整理助手', description: '汇总工作记录，生成结构清晰的周报初稿。', category: '行政办公', owner: '我的智能体', status: '草稿', icon: BriefcaseBusiness, tone: 'amber' },
  { name: '客服回复助手', description: '参考服务规范，生成准确、友好的客户回复。', category: '客服应答', owner: '客户成功团队', status: '已发布', icon: ShieldCheck, tone: 'violet' },
  { name: '数据摘要助手', description: '提取表格中的关键变化，生成可读的业务摘要。', category: '数据分析', owner: '数据团队', status: '已发布', icon: Bot, tone: 'sky' },
  { name: '营销文案助手', description: '根据产品信息生成多种渠道的文案草稿。', category: '文案创作', owner: '市场团队', status: '已发布', icon: Sparkles, tone: 'rose' },
];

const toneClasses: Record<string, string> = {
  indigo: 'bg-indigo-50 text-indigo-600 dark:bg-indigo-500/15 dark:text-indigo-300', emerald: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/15 dark:text-emerald-300', amber: 'bg-amber-50 text-amber-600 dark:bg-amber-500/15 dark:text-amber-300', violet: 'bg-violet-50 text-violet-600 dark:bg-violet-500/15 dark:text-violet-300', sky: 'bg-sky-50 text-sky-600 dark:bg-sky-500/15 dark:text-sky-300', rose: 'bg-rose-50 text-rose-600 dark:bg-rose-500/15 dark:text-rose-300',
};

export default function Agents() {
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const viewMode = pathname === '/agents/templates' ? 'templates' : pathname === '/team/agents' ? 'team' : pathname === '/agents/mine' ? 'mine' : 'all';
  const [category, setCategory] = useState('全部');
  const [query, setQuery] = useState('');
  const [selectedAgent, setSelectedAgent] = useState<Agent | null>(null);
  const [favorites, setFavorites] = useState<string[]>([]);
  const [showCreate, setShowCreate] = useState(pathname === '/agents/new');
  const [createdName, setCreatedName] = useState('');
  const [created, setCreated] = useState<string[]>([]);
  const SelectedIcon = selectedAgent?.icon;
  const visibleAgents = useMemo(() => {
    if (viewMode === 'templates') return agents.filter((agent) => agent.owner !== '我的智能体');
    if (viewMode === 'team') return agents.filter((agent) => agent.owner !== '我的智能体' && agent.owner !== '市场团队');
    if (viewMode === 'mine') return agents.filter((agent) => agent.owner === '我的智能体');
    return agents;
  }, [viewMode]);
  const filteredAgents = useMemo(() => visibleAgents.filter((agent) => (category === '全部' || agent.category === category) && `${agent.name}${agent.description}${agent.owner}`.toLowerCase().includes(query.toLowerCase())), [category, query, visibleAgents]);
  const pageTitle = viewMode === 'templates' ? '官方模板' : viewMode === 'team' ? '团队智能体' : viewMode === 'mine' ? '我创建的智能体' : '智能体广场';
  const pageDescription = viewMode === 'templates' ? '从经过验证的业务场景模板开始，快速创建适合团队的智能体。' : viewMode === 'team' ? '查看团队共享的工作助手，直接使用已有能力。' : viewMode === 'mine' ? '管理你创建的智能体草稿和已发布版本。' : '找到适合当前工作的智能体，直接使用或从模板开始创建。';

  return (
    <div className="mx-auto max-w-7xl space-y-6 p-5 sm:p-8">
      <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface-1)] p-6 shadow-[var(--shadow-sm)] sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--brand)]">能力中心</p><h2 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">{pageTitle}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--text-muted)]">{pageDescription}</p></div><button type="button" onClick={() => setShowCreate(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--brand)] px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[var(--brand-hover)]"><Plus className="h-4 w-4" />创建智能体</button></div><div className="relative mt-7 max-w-xl"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索智能体、场景或团队" className="h-11 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] pl-10 pr-4 text-sm text-[var(--text)] outline-none placeholder:text-[var(--text-muted)] focus:border-[var(--brand)] focus:ring-2 focus:ring-[var(--brand)]/15" /></div></section>
      <div className="flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="智能体场景分类">{categories.map((item) => <button key={item} type="button" role="tab" aria-selected={category === item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-medium transition ${category === item ? 'bg-[var(--brand)] text-white' : 'border border-[var(--border)] bg-[var(--surface-1)] text-[var(--text-secondary)] hover:border-[var(--brand)] hover:text-[var(--brand)]'}`}>{item}</button>)}</div>
      <section><div className="mb-4 flex items-center justify-between"><div><h3 className="text-base font-semibold">推荐智能体</h3><p className="mt-1 text-xs text-[var(--text-muted)]">基于团队常用场景为你推荐</p></div><span className="text-xs text-[var(--text-muted)]">{filteredAgents.length} 个结果</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filteredAgents.map((agent) => { const Icon = agent.icon; const favorite = favorites.includes(agent.name); return <article key={agent.name} onClick={() => setSelectedAgent(agent)} className="group flex min-h-[210px] cursor-pointer flex-col rounded-xl border border-[var(--border)] bg-[var(--surface-1)] p-5 transition hover:-translate-y-0.5 hover:border-[var(--brand)] hover:shadow-[var(--shadow-sm)]"><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-lg ${toneClasses[agent.tone]}`}><Icon className="h-5 w-5" /></span><div className="flex items-center gap-2"><button type="button" onClick={(event) => { event.stopPropagation(); setFavorites((items) => favorite ? items.filter((name) => name !== agent.name) : [...items, agent.name]); }} className={`rounded-md p-1.5 ${favorite ? 'text-rose-500' : 'text-[var(--text-muted)] opacity-0 group-hover:opacity-100'}`} aria-label={favorite ? '取消收藏' : '收藏智能体'}><Heart className="h-4 w-4" fill={favorite ? 'currentColor' : 'none'} /></button><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${agent.status === '草稿' ? 'bg-[var(--warning-bg)] text-[var(--warning)]' : 'bg-[var(--success-bg)] text-[var(--success)]'}`}>{agent.status}</span></div></div><h4 className="mt-5 text-base font-semibold">{agent.name}</h4><p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--text-muted)]">{agent.description}</p><div className="mt-auto flex items-center justify-between pt-5"><span className="text-xs text-[var(--text-muted)]">{agent.category} · {agent.owner}</span><span className="inline-flex items-center gap-1 text-xs font-semibold text-[var(--brand)] opacity-0 transition group-hover:opacity-100">查看详情<ChevronRight className="h-3.5 w-3.5" /></span></div></article>; })}</div>{filteredAgents.length === 0 ? <div className="rounded-xl border border-dashed border-[var(--border)] p-12 text-center text-sm text-[var(--text-muted)]">没有找到匹配的智能体，试试其他关键词或场景。</div> : null}</section>
      <section className="grid gap-4 md:grid-cols-3"><NavLink to="/agents/mine" className="rounded-xl border border-dashed border-[var(--border)] bg-[var(--surface-1)] p-5 hover:border-[var(--brand)]"><Bot className="h-5 w-5 text-[var(--brand)]" /><h3 className="mt-4 text-sm font-semibold">我创建的智能体</h3><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">管理个人草稿和已发布的智能体</p></NavLink><NavLink to="/agents/templates" className="rounded-xl border border-dashed border-[var(--border)] bg-[var(--surface-1)] p-5 hover:border-[var(--brand)]"><Sparkles className="h-5 w-5 text-[var(--brand)]" /><h3 className="mt-4 text-sm font-semibold">官方模板</h3><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">从经过验证的场景模板开始</p></NavLink><NavLink to="/team/agents" className="rounded-xl border border-dashed border-[var(--border)] bg-[var(--surface-1)] p-5 hover:border-[var(--brand)]"><UsersRound className="h-5 w-5 text-[var(--brand)]" /><h3 className="mt-4 text-sm font-semibold">团队智能体</h3><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">查看团队共享的工作助手</p></NavLink></section>
      {selectedAgent && SelectedIcon ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="presentation" onClick={() => setSelectedAgent(null)}><section role="dialog" aria-modal="true" aria-label={`${selectedAgent.name} 详情`} onClick={(event) => event.stopPropagation()} className="w-full max-w-md rounded-2xl border border-[var(--border)] bg-[var(--surface-1)] p-6 shadow-2xl"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 place-items-center rounded-xl ${toneClasses[selectedAgent.tone]}`}><SelectedIcon className="h-5 w-5" /></span><div><h3 className="text-lg font-semibold">{selectedAgent.name}</h3><p className="text-xs text-[var(--text-muted)]">{selectedAgent.category} · {selectedAgent.owner}</p></div></div><button type="button" onClick={() => setSelectedAgent(null)} className="rounded-md p-2 text-[var(--text-muted)] hover:bg-[var(--bg-hover)]" aria-label="关闭详情"><X className="h-4 w-4" /></button></div><p className="mt-6 text-sm leading-6 text-[var(--text-secondary)]">{selectedAgent.description}</p><div className="mt-5 rounded-xl bg-[var(--bg-elevated)] p-4 text-xs leading-5 text-[var(--text-muted)]"><p className="font-semibold text-[var(--text)]">使用前你需要知道</p><p className="mt-1">该智能体会根据你提供的内容生成结果，涉及外部发送或数据修改时会请求确认。</p></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setSelectedAgent(null)} className="rounded-lg border border-[var(--border)] px-4 py-2 text-sm font-medium">取消</button><button type="button" onClick={() => navigate('/copilot', { state: { agentName: selectedAgent.name } })} className="inline-flex items-center gap-2 rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white"><Play className="h-4 w-4" />开始使用</button></div></section></div> : null}
      {showCreate ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="presentation" onClick={() => setShowCreate(false)}><form role="dialog" aria-modal="true" aria-label="创建智能体" onClick={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); if (createdName.trim()) { setCreated((items) => [...items, createdName.trim()]); setCreatedName(''); setShowCreate(false); } }} className="w-full max-w-md rounded-2xl border border-[var(--border)] bg-[var(--surface-1)] p-6 shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">创建智能体</h3><button type="button" onClick={() => setShowCreate(false)} className="rounded-md p-2 text-[var(--text-muted)] hover:bg-[var(--bg-hover)]" aria-label="关闭创建窗口"><X className="h-4 w-4" /></button></div><p className="mt-2 text-sm text-[var(--text-muted)]">先填写名称，稍后可以继续配置目标、知识和工具。</p><label className="mt-6 block text-sm font-medium">智能体名称<input autoFocus value={createdName} onChange={(event) => setCreatedName(event.target.value)} placeholder="例如：会议纪要助手" className="mt-2 h-11 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] px-3 text-sm outline-none focus:border-[var(--brand)]" /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-lg border border-[var(--border)] px-4 py-2 text-sm font-medium">取消</button><button type="submit" disabled={!createdName.trim()} className="inline-flex items-center gap-2 rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"><Check className="h-4 w-4" />保存草稿</button></div></form></div> : null}
    </div>
  );
}
